# Generated by Django 5.2.2 on 2025-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='deposito_padrao',
            new_name='id_deposito_padrao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='fornecedor',
            new_name='id_fornecedor',
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(max_length=10),
        ),
    ]
