# Generated by Django 5.2.2 on 2025-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_rename_deposito_padrao_produto_id_deposito_padrao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='deposito',
            new_name='id_deposito',
        ),
        migrations.RenameField(
            model_name='movimentacao',
            old_name='fornecedor',
            new_name='id_fornecedor',
        ),
        migrations.RenameField(
            model_name='movimentacao',
            old_name='usuario',
            new_name='id_usuario',
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
